version: '3.1'

services:

  postgresql:
    container_name: postgresql
    image: postgres
    env_file:
      - .env
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgresql/dumps:/code/dumps
      - ./postgresql/data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:8080"
